### ISSUE TITLE
Strange behavior for W25Q256JV with Arduino Uno

### ISSUE THREAD

**Issue by swapnilsayansaha** [PaulStoffregen/SerialFlash#69] opened 2020-08-03 21:47 UTC
I connected a Winbond W25Q256JV to Arduino Uno. The example codes (e.g. RawHardwareTest) shows that the flash has 32 Mb of memory, which is not correct (the flash has eight 32 Mb sectors, totaling 256 Mb). P.S. My bad, I got confused. 256 Mb is 32 MB. This is fine.

Secondly, the example code (RawHardwareTest) gets stuck at:  
chipsize = SerialFlash.capacity(buf);

**Comment by FrankBoesing** [comment] 2020-08-04 11:12
A) 256Mbit are 32M Bytes. 
B) I don't understand. You say RawHardwareTest shows a size (32Mb - which is correct) ,and "secondly it gets stuck at SerialFlash.capacity(buf)".  If it would stuck, it could'nt display a size. Then, the code used is here: https://github.com/PaulStoffregen/SerialFlash/blob/master/SerialFlashChip.cpp#L452 - there is no way it can stuck.

**Comment by swapnilsayansaha** [comment] 2020-08-04 16:47
Hi, thanks for pointing out. Sorry I got confused. The code gets stuck right after capacity is shown here:

```
Serial.println("Reading Chip...");
 memset(buf, 0, sizeof(buf));
 memset(sig, 0, sizeof(sig));
 memset(buf2, 0, sizeof(buf2));
```

**Comment by mykola-nikoliuk** [comment] 2021-02-24 19:41
The same behavior here with ATmega328P-AU

**Comment by mykola-nikoliuk** [comment] 2021-02-24 20:03
Ok, the problem is that lib overuse "strings" that stored in RAM. Arduino or other atmegas do not have enough memory for this.
Just wrap all the logs with F() like Serial.print(F("Your logs")). This will reduce load and test starts work like a charm.

**Comment by PaulStoffregen** [comment] 2021-03-03 10:55
How does this look?
https://github.com/PaulStoffregen/SerialFlash/commit/8c310813003388455b8738bddda34eb03f3a3ef3

Does it fully solve this issue?

**Comment by FrankBoesing** [comment] 2021-03-03 11:31
I don't think the MP3payer works with the Uno...

Am 3. März 2021 11:56:07 MEZ schrieb Paul Stoffregen <notifications@github.com>:
>How does this look?
>https://github.com/PaulStoffregen/SerialFlash/commit/8c310813003388455b8738bddda34eb03f3a3ef3
>
>Does it fully solve this issue?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulStoffregen/SerialFlash/issues/69#issuecomment-789626135

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by PaulStoffregen** [comment] 2021-03-03 21:04
LOL

I'm going to assume this issue is resolved and close it now.  If anyone disagrees, just reply with details.

**Closed as completed by PaulStoffregen** 2021-03-03 21:04 UTC

**Comment by msaid2010** [comment] 2023-05-18 13:58
hi I use Atmega128 and I made level shifting for W25Q64 when I tested the code ( RawHardwareTest ) it always fail 
![image](https://github.com/PaulStoffregen/SerialFlash/assets/45630551/e229868c-cb3d-436c-9cf4-8d167da9f504)
is there any problem in the Hardware ???
or What the problem ?
